### ISSUE TITLE
Can you upload it to curseforge so I can use it in a modpack?

### ISSUE THREAD

**Issue by Jetpack-Cat** [HO-Artisan/BurstDoorOpen#1]

**Comment by chemiofitor** [comment]
No problem, bro.
I will do it.

**Comment by TexBlock** [comment]
@chemiofitor will upload on curseforge

**Comment by chemiofitor** [comment]
Please wait for review.
https://legacy.curseforge.com/minecraft/mc-mods/burst-door-open.

**Comment by chemiofitor** [comment]
Emmmm,maybe I should close this after the approval.
